### ISSUE TITLE
add media query to make page responsive

### ISSUE THREAD

**Issue by saqib40** [saqib40/JS-Documentation-Page#1]

**Comment by mayuribotre15** [comment]
Hey @saqib. Can I work on it?

I can make your page responsive using media query.

Check out my work at:
https://mayuribotre15.github.io/DemoHomePage/

**Comment by saqib40** [comment]
> Hey @saqib. Can I work on it?
> 
> I can make your page responsive using media query.
> 
> Check out my work at:
> https://mayuribotre15.github.io/DemoHomePage/



> Hey @saqib. Can I work on it?
> 
> I can make your page responsive using media query.
> 
> Check out my work at:
> https://mayuribotre15.github.io/DemoHomePage/

go for it, the issue is pretty much simple but if you get stuck anywhere you can always ask me here

**Comment by mayuribotre15** [comment]
Thank you, I will complete the work within a day.
Get back to you as soon as possible
